class Autogenerated {
  Autogenerated({required this.sId, required this.friendRequests});

  final String sId;
  final List<dynamic> friendRequests;

  factory Autogenerated.fromJson(json) {
    return Autogenerated(
        sId: json['_id'] ?? '', friendRequests: json['friendRequests'] ?? '');
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['_id'] = this.sId;
    data['friendRequests'] = this.friendRequests;
    return data;
  }
}
