import 'dart:convert';
import 'package:bookd/provider/login_data.dart';
import 'package:bookd/screens/friends_profile.dart';
import 'package:bookd/screens/login.dart';
import 'package:bookd/screens/profile.dart';
import 'package:bookd/services/auth_services.dart';
import 'package:bookd/services/user_details.dart';
import 'package:bookd/widgets/appbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:flutter_svg/svg.dart';
import 'package:bookd/widgets/form_field.dart';
import 'package:bookd/widgets/button.dart';
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:bookd/screens/email_verification.dart';
import 'package:http/http.dart' as http;
import 'package:bookd/models/user.dart';

class Notifications extends StatefulWidget {
  const Notifications({super.key});

  @override
  State<Notifications> createState() {
    return _Notifications();
  }
}

class _Notifications extends State<Notifications> {
  final UserDetailsService userDetailsService = UserDetailsService();
  @override
  Widget build(context) {
    final friend = Provider.of<FriendProvider>(context).autogenerated;
    List<Details> details;
    return Scaffold(
        appBar: AppBar(
          title: Text('Notifications'),
        ),
        body: Column(
          children: [
            Expanded(
              child: ListView.builder(
                  itemCount: friend.friendRequests.length,
                  itemBuilder: (context, index) {
                    return Container(
                      margin: EdgeInsets.only(top: 3),
                      child: ListTile(
                        visualDensity: VisualDensity.adaptivePlatformDensity,
                        tileColor: Theme.of(context)
                            .colorScheme
                            .secondary
                            .withOpacity(0.6),
                        title: Text(
                            'You have a new event added to your calendar. Check it out !'),
                        subtitle: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Yesterday'),
                          ],
                        ),
                        leading: Material(
                          shape: CircleBorder(
                              side: BorderSide(color: Colors.white, width: 2)),
                          elevation: 0,
                          child: CircleAvatar(
                            radius: 30,
                            backgroundColor: Color.fromARGB(255, 222, 221, 221),
                            child: Icon(Icons.notifications_active, size: 30),
                          ),
                        ),
                        onTap: () async {
                          http.Response res =
                              await userDetailsService.getFriend(
                                  email:
                                      friend.friendRequests[index].toString());

                          if (res.statusCode == 200) {
                            List<dynamic> lres = jsonDecode(res.body);

                            details =
                                lres.map<Details>(Details.fromJson).toList();
                            print(details[index]);

                            Navigator.of(context).push(MaterialPageRoute(
                              builder: (context) {
                                return FriendsProfile(
                                  friend: details[index],
                                  followstatus: "",
                                  friendstatus: "",
                                );
                              },
                            ));
                          }
                        },
                      ),
                    );
                  }),
            ),
          ],
        ));
  }
}
