import 'dart:convert';
import 'package:bookd/models/allfriend.dart';
import 'package:bookd/models/friend.dart';
import 'package:bookd/models/user.dart';
import 'package:bookd/models/user_details.dart';
import 'package:flutter/material.dart';

class UserProvider extends ChangeNotifier {
  UserDetails _user = UserDetails(
      id: '',
      username: '',
      email: '',
      password: '',
      phone: '',
      token: '',
      otp: '',
      friend: '');

// instance of _user
  UserDetails get user => _user;

// user is json and _user is UserDetails object
  void setUser(String user) {
    _user = UserDetails.fromJson(user);
    notifyListeners();
  }

  void setUserModel(UserDetails user) {
    _user = user;
    notifyListeners();
  }
}

class FriendProvider extends ChangeNotifier {
  List<Autogenerated> _autogenerated = [
    Autogenerated(sId: '', friendRequests: [])
  ];

// instance of _user
  Autogenerated get autogenerated => _autogenerated[0];

// user is json and _user is UserDetails object
  void setFriend(String autogenerated) {
    _autogenerated = jsonDecode(autogenerated)
        .map<Autogenerated>(Autogenerated.fromJson)
        .toList();
    print(_autogenerated[0].friendRequests);
    notifyListeners();
  }
}

class AllProvider extends ChangeNotifier {
  List<Details> _details = [
    Details(id: '', username: '', email: '', phone: '')
  ];

// instance of _user
  List<Details> get details => _details;

// user is json and _user is UserDetails object
  void setFriend(String allfriend) {
    _details = jsonDecode(allfriend).map<Details>(Details.fromJson).toList();
    print(_details);
    notifyListeners();
  }
}

class AllFriendProvider extends ChangeNotifier {
  List<Allfriend> _allfriend = [Allfriend(sId: '', friends: [])];
  List<Allfollow> _allfollow = [Allfollow(sId: '', follows: [])];

// instance of _user
  Allfriend get allfriend => _allfriend[0];
  Allfollow get allfollow => _allfollow[0];

// user is json and _user is UserDetails object
  void setFriend(String allfriend) {
    _allfriend =
        jsonDecode(allfriend).map<Allfriend>(Allfriend.fromJson).toList();
    print(_allfriend[0].friends);
    notifyListeners();
  }

  void setFollow(String allfollow) {
    _allfollow =
        jsonDecode(allfollow).map<Allfollow>(Allfollow.fromJson).toList();
    print(_allfollow[0].follows);
    notifyListeners();
  }
}
